In [29]:
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt
import csv

# Open and read a CSV file
with open('xyz_ECOSTRESS.csv', mode='r') as file:
    reader = csv.reader(file)
    
    # Ignorer la première ligne (en-tête)
    next(reader)
    XYZ = np.array([[float(value) for value in row[1:]]  for row in reader])
    
#On récupère les colonnes X,Y,Z
X = XYZ[:, 0]
X_ = X.reshape(653, 1)
   
Y = XYZ[:, 1]
Y_ = Y.reshape(653, 1)
    
Z = XYZ[:, 2]
Z_ = Z.reshape(653, 1)

#On compile les 3 matrices
XYZ_ = np.vstack((X_, Y_, Z_))
    
    
with open('rho_ECOSTRESS_S2A.csv', mode='r') as file:
    csv_reader = csv.reader(file)
    
    # Ignorer la première ligne (en-tête)
    next(csv_reader)
    
    # Ignorer la première colonne (en-tête)
    A_x = np.array([[float(value) for value in row[1:]]  for row in csv_reader])
A_y = A_x.copy()
A_z = A_x.copy()

T = np.array([[0.371, 0.362,0.268 ],[0.174,0.587, 0.240],[-0.043,-0.427, 1.463]]).T
T_X = np.array([[0.371],[0.174],[-0.043]])
T_Y = np.array([[0.362],[0.587],[-0.427]])
T_Z = np.array([[0.268],[0.240],[1.463]])



A_x[:, 0] *= T_X[0][0]  # Multiplier la colonne 1 par T_X[0][0] 
A_x[:, 1] *= T_X[1][0]   # Multiplier la colonne 2 par T_X[1][0] 
A_x[:, 2] *= T_X[2][0]   # Multiplier la colonne 3 par T_X[2][0] 

A_y[:, 0] *= T_Y[0][0]  
A_y[:, 1] *= T_Y[1][0]  
A_y[:, 2] *= T_Y[2][0] 

A_z[:, 0] *= T_Z[0][0]  
A_z[:, 1] *= T_Z[1][0]  
A_z[:, 2] *= T_Z[2][0] 

#On compile les 3 matrices
A = np.vstack((A_x, A_y, A_z))


P = np.eye(len(A))



def moindre_carre(B,A,P):
    N = (A.T)@P@A
    K = (A.T)@P@B
    X = np.linalg.inv(N)@K
    V = B - A @ X
    n = len(A)
    p = len(A[0])
    sigma_2 = V.T@P@V/(n-p)
    Q = (sigma_2)*(np.linalg.inv(A.T@P@A))
    return X, Q, sigma_2, V

def ecart_type(l):
    EcartT = 0
    n = len(l)
    moy = sum(l)/n
    for i in range(n):
         EcartT += (l[i] - moy)**2
    return sqrt(EcartT/(n-1))





X_sortie, Q, sigma_2, V = moindre_carre(XYZ_,A, P)
print('Constant :\n', X_sortie)
print('Résidu :\n', V)
print('sigma2 :\n', sigma_2)

#plt.scatter(A,Y, c = 'black', s = 5)
# y = X[0]*A_1 + X[1]
# plt.plot(A_1,y, c = 'red')
# plt.title("Régression linéaire DR1")
# plt.xlabel("Valeurs t")
# plt.ylabel("Valeurs de y")
# plt.text(-150,20, 'f"a = {X[0]}, b = {X[1]}')
# plt.show()

Constant :
 [[2.57511992]
 [0.47153185]
 [0.09773047]]
Résidu :
 [[0.02697357]
 [0.04059487]
 [0.06664684]
 ...
 [0.14490365]
 [0.14344076]
 [0.1441791 ]]
sigma2 :
 [[0.00044642]]


array([[ 0.07666581,  0.15377442, -0.12856703],
       [ 0.04035651,  0.08489842, -0.09521462],
       [ 0.01574762,  0.04797217, -0.08593022],
       ...,
       [ 0.35369865,  0.57006422, -0.40133804],
       [ 0.35899145,  0.58088571, -0.41738929],
       [ 0.35646674,  0.57570674, -0.40937142]])

In [ ]:
print(A)

In [ ]:
np.shape(A.T)


In [22]:
A = np.vstack((A_x, A_y, A_z))
print(np.shape(A))

(1959, 3)


In [ ]:
A.T@X_